data:
  scenario: straight #straight, bifurcation, bend90 or branch
  model_dir: model/
preprocess:
  img_height: 192 #384 original = 389, make divisible by 2 multiple times
  img_width: 256 #512 original = 515, make divisible by 2 multiple times
  channels: 1 #3=RGB, 1=GRAYSCALE
AE:
  filters: 32 #128 is not possible, allocating tensor error
  z_num: 100
  num_conv:  3 #4-5 in Deep Fluids
  conv_k: 3
  last_k: 1 #channels
  repeat: 4 #0 = calculated = 6 (previously 4), more repeats is more downsampling, less trainable parameters
  training:
    patience: 25
    batch_size: 36
    epochs: 250
TS:
  architecture: NN #NN GRU LSTM
  node_num: 512 #512 used in deep Fluids
  training:
    dropout: 0.1
    batch_size: 10
    epochs: 200

