data:
  scenario: bifurcation #straight, bifurcation, bend or branch
  model_dir: model/
  model: model/total_bifurcation_BS18_E250_LSTM
preprocess:
  img_height: 192 #384 original = 389, make divisible by 2 multiple times
  img_width: 256 #512 original = 515, make divisible by 2 multiple times
  channels: 1 #3=RGB, 1=GRAYSCALE
AE:
  filters: 16 #hypertuned = 24, 128 is not possible, allocating tensor error
  z_num: 150   #hypertuned = 75
  num_conv:  3 #previously 3, 4-5 in Deep Fluids
  conv_k: 3
  last_k: 1 #channels
  repeat: 4 #hypertuned = 2, 0 = calculated = 6 (previously 4), more repeats is more downsampling, less trainable parameters
  training:
    patience: 20
    batch_size: 18
    epochs: 250
TS:
  window:
      input: 1
      shift: 1
      label: 5
  architecture: LSTM #NN GRU LSTM
  node_num: 512 #hypertuned = 1000, 512 used in deep Fluids
  num_layers: 2 #2 in Deep Fluids
  training:
    dropout: 0.1
    batch_size: 10
    epochs: 200

